import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getTheme } from "./lib/getTheme";
import Navbar from "../components/navbar/Navbar";
import Footer from "../components/footer/Footer";
import { ThemeContextProvider } from "./context/ThemeContext";
import ThemeProvider from "./providers/ThemeProvider";
import Cursor from "../components/cursor/Cursor";
import AuthProvider from "./providers/AuthProvider";
import { LangProvider } from "./context/LangProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Antenna's Transmission",
  description: "Generated by create next app",
};

export default function RootLayout({children, params: {locale}} : {children:React.ReactNode, params: {locale: string}}) {
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
        {/* <ThemeContextProvider>
          <ThemeProvider> */}
        <script
          dangerouslySetInnerHTML={{ __html: getTheme }}
        />
        <div className="containerA">
          <div className="wrapper">
            <Cursor />
            <Navbar />

            {children}
 
            <Footer />
          </div>
        </div>
        {/* </ThemeProvider>
        </ThemeContextProvider> */}
        </AuthProvider>
      </body>
    </html>
  );
}
